### ISSUE TITLE
bug when connecting to remote instance

### ISSUE THREAD

**Issue by claragpalacios** [MISP/misp-book#121]
Good morning,

When I connect to a remote instance, in this case with "https://misp.first.org" it's necessary to obtain a valid authentication key from the remote instance (Authkey of a user who is a sync user).

The user I'm employing is "user" no "sync user", so when I click on the Run button it returns the following error: "Remote user not a sync user".
However it's able to share the events of the remote instance with my instance.

I think this is a bug that should be corrected.

I'm attaching both images of the error and the events that my instance has received from the frist.org instance as well as from the jobs.

My version of Misp is 2.4.91.

Thank you very much in advance.

I'm looking forward to hear from you.

Greetings.

![first](https://user-images.githubusercontent.com/36531137/41911273-7eb1bcae-794c-11e8-9ee7-7b14b513c33e.jpg)
![events](https://user-images.githubusercontent.com/36531137/41911275-81007e32-794c-11e8-8979-4f20ed53f16a.jpg)
![jobs](https://user-images.githubusercontent.com/36531137/41911280-82f16fe4-794c-11e8-8993-0c6a5792f561.jpg)

**Comment by SteveClement** [comment]
Dear @claragpalacios 

This repository is for the Documentation of MISP only.

Please open an issue here if it is not solved yet:

https://github.com/MISP/MISP/issues/
