### ISSUE TITLE
Missing feed information downloading with get_feeds_list()

### ISSUE THREAD

**Issue by EdAtt** [MISP/misp-book#149]
When I run a pymisp "get_feeds_list()" request, and compare the results against the MISP>Sync Actions>List Feeds UI page, the results do not match? There are entries on the UI page that are not showing up in the "get_feeds_list()" data. Those entries that do not not show up have an ID number and everything looks OK. As a matter of fact, one entry was entered twice but with different Names. One shows up in the "get_feeds_list()" but the other does not. 

While testing I get these results:  get_feeds_list() returns 60 records,  There are 64 records listed on the MISP feeds web page and when I ask for a count(*) from the database, I get 64.

What am I missing? I would assume that the results from the "get_feeds_list()" would be exactly the same  as what is in the database.

**Comment by github-germ** [comment]
The `misp` database `feeds` table has a column named `default` which appears to be set to `1` for feeds out-of-the-box from the MISP team; set to `0` for `custom feeds` added locally.

**Comment by EdAtt** [comment]
Then why doesn't "get_feeds_list()" return everything?  Is there another MISP request that will pull everything?

**Comment by iglocska** [comment]
It was truncating the list to 60 elements, similarly to the UI. It should no longer do that.
