### ISSUE TITLE
Misp-book: general-layout =>drop-down menus explanations

### ISSUE THREAD

**Issue by hibouu** [MISP/misp-book#17]
I up to date misp-book/general-layout/

In the menu bar "layout Filter", it seems to be a new tab "Warning List", who is not documented. What is it and for what can I use that? (Yeah, I know that it will shows a list of warnings, but I don't know why it is usefull).

**Comment by adulau** [comment]
Good question. The current documentation for the MISP warning list is available on the following slides:

https://www.circl.lu/assets/files/misp-training/first2016/2-MISP-Taxonomies.pdf
from page 12 to 14. You are most probably interested in the page 12 describing the issue with false-positive and what the warning lists try to limit such false-positive by warning contributors of potential false-positive.

The README of the warning-lists is also a good introduction. https://github.com/MISP/misp-warninglists

I hope this helps and thank you for your work.

**Comment by hibouu** [comment]
Thanks. 
Who can I find some explanation about Sharing Group? especially, if I've right understand, they  restrain the scope of peoples they have access to some events?

**Comment by hibouu** [comment]
Otherwise, when I look at Sync Actions => List Server, I have an error message in my VM. Have you that IRL? 
![pb list server](https://cloud.githubusercontent.com/assets/11872380/17451030/07fde43c-5b64-11e6-8ecc-a7b25cc0564e.png)

Idem for the list feeds => Action => http://192.168.56.50/feeds/previewIndex/1
![pb_feed](https://cloud.githubusercontent.com/assets/11872380/17451071/5544e6fa-5b64-11e6-991d-81d738a0ff1c.jpg)

**Comment by rotanid** [comment]
please open a separate issue for the misp software itself if you encounter such problems and provide as much details as possible.
if you create a new issue for misp, there is a template guiding you which information we might need to find the origin.

**Comment by hibouu** [comment]
ok. Thanks.
