### ISSUE TITLE
Can filter by date

### ISSUE THREAD

**Issue by didniv18** [MISP/misp-book#171]
Hi ,
Im trying to filter my request by date but its not working, every day i put on the header gives me the same result.

My code :

from requests.auth import HTTPBasicAuth
import requests
from datetime import date

url = "http://192.168.1.104:81/events/index"
print(url)
headers = {"Authorization": "apikey","Accept": "application/json","Content-Type": "application/json"}
body = {"searchDatefrom": "2019-01-01"}

req = requests.post(url, headers=headers,json=body)

Thanks ,
Niv

**Comment by rommelfs** [comment]
According to the REST search documentation at http://192.168.1.104:81/servers/rest
you should be using 'datefrom'. Could you test with the REST client first and export and try the code from there?

**Comment by didniv18** [comment]
It looks better , but the file that was created can't be imported to other Misp.
The error I get is : 
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

**Comment by rommelfs** [comment]
Please elaborate what you are doing.

**Comment by didniv18** [comment]
I want to export events from one misp to other misp using python .

**Comment by rommelfs** [comment]
And the error is on import? Please open a new issue in this case.
Btw., MISP has a synchronisation protocol which you might want to use in this case.

**Comment by didniv18** [comment]
Its not on the same network , so its impossible.
