### ISSUE TITLE
MISP Publish Alert Filter

### ISSUE THREAD

**Issue by pjotawake** [MISP/misp-book#178]
Hi,

The new filter functionality appearing in 2.4.117 does not seem to be documented in the MISP-book.

Maybe the text and screenshots in the attached RTF can be added.

Best regards
Peter

[MISP Publish Alert Filter (EN).zip](https://github.com/MISP/misp-book/files/3940262/MISP.Publish.Alert.Filter.EN.zip)

**Comment by SteveClement** [comment]
Thanks, I added it to the administration section.
