### ISSUE TITLE
Explain "sould" as used in book-convention

### ISSUE THREAD

**Issue by bernhardreiter** [MISP/misp-book#182]
"Book Convention" has

>  the inadvertent sould of a piece of software

What does "sould" mean here? (It does not have an entry in wiktionary)

**Comment by SteveClement** [comment]
Seems like a typo

**Comment by SteveClement** [comment]
fixed in #185

**Comment by bernhardreiter** [comment]
@SteveClement thanks! ("soul" would have been the most likely guess, but there are many special IT concepts, so it was better clarified explicitely.)_
