### ISSUE TITLE
Ellaborate on distribution level decrement while synchronizing

### ISSUE THREAD

**Issue by mokaddem** [MISP/misp-book#188]
Explain the different between PULL and PUSH and the benefit of using these two in conjunction.

**Comment by Wachizungu** [comment]
I added something here https://www.circl.lu/doc/misp/sharing/#syncing-scenarios-with-communities-distribution (forgot to link this particular issue as well).

I am not sure what to say about "the benefit of using these two in conjunction." though.

**Comment by mokaddem** [comment]
What I had in mind was the following:
- PUSH: It can provide a seemingly real time experience. If a PUSH connection is enabled, data created (and synchronized from other peers) will be synchronized as fast as possible
- PULL: You can choose whenever you want to fetch the remote data. It also works great in conjunction with PUSH if unexpected issues preventing PUSH operations happen. For example, dead workers, connectivity drops, ...
