### ISSUE TITLE
Document ZeroMQ plugin

### ISSUE THREAD

**Issue by elhoim** [MISP/misp-book#20]

**Comment by RichieB2B** [comment]
+1 on this one.. Google gave me this page :-(

**Comment by iglocska** [comment]
@adulau is working on it already - and new features are coming ;)

**Comment by adulau** [comment]
Google is not up-to-date (I just committed this morning ;-), Indeed. https://github.com/MISP/misp-book/tree/master/misp-zmq  Indeed I'll close it.
