### ISSUE TITLE
Some table of contents links don't match heading

### ISSUE THREAD

**Issue by PROTechThor** [MISP/misp-book#203]
The table of contents links at the top of each page don't neccessariily match heading. As such, when I click some links, the page doesn't jump to the topic. 

For example: the table of contents link for one section is https://www.circl.lu/doc/misp/faq/#why-do-i-see-%27the-request-has-been-black-holed%27-when-i-submit-forms?, but the actual heading link is https://www.circl.lu/doc/misp/faq/#why-do-i-see-the-request-has-been-black-holed-when-i-submit-forms 

This issue is very prevalent on the FAQ page, due to the questions marks at the end of heading. This issue can be be fixed by stripping symbols like ? and ' from the table of contents links. I'm not sure if this is manual work or if it can be done automatically.

**Comment by Wachizungu** [comment]
What is used to generate the documentation based on the markdown (I'm guessing it's a bug in the software used for that)?

**Comment by Wachizungu** [comment]
It's a known issue with the toc plugin.

https://www.npmjs.com/package/gitbook-plugin-atoc might be an alternative, the links work with that. It's also not maintained anymore it seems though :(. Unfortunately the other alternatives all seem to have their own flaws in terms of design in my opinion.

**Comment by PROTechThor** [comment]
@Wachizungu 

Thank you for investigating this issue. @adulau recently migrated the website to Honkit, a Gitbook fork. But the issue still persists. The problem lies in the fact that the actual links trim punctuation marks like "?", but the toc links do not. 

> https://www.npmjs.com/package/gitbook-plugin-atoc might be an alternative, the links work with that. It's also not maintained anymore it seems though :(. Unfortunately the other alternatives all seem to have their own flaws in terms of design in my opinion.

Will it be better to use an unmaintained plugin or let the issue persist? Seems like a tradeoff between security and usability. @adulau @iglocska Thoughts, guys?

@Wachizungu Do you think it's possible to manually set the TOC links? It's more work and seems like a future maintenance headache (when the topics get changed), but it may be our only choice.

**Comment by PROTechThor** [comment]
@adulau That was a quick fix. Thanks! :)

**Comment by adulau** [comment]
@PROTechThor Thanks a lot for idea. I tried `atoc` and it works indeed well (even if the module is unmaintained). The latest output generated should indeed fix the issue. Diving into unmaintained gitbook plugin, it's like being India Jones in a pyramid.

**Comment by PROTechThor** [comment]
@adulau There are a few long links that get cropped and don't work, but it's not a big deal, since they can be fixed by modifying the headings.

**Comment by PROTechThor** [comment]
> @adulau There are a few long links that get cropped and don't work, but it's not a big deal, since they can be fixed by modifying the headings.

I can make a quick PR for this

**Comment by PROTechThor** [comment]
Nevermind. All good now :)
