### ISSUE TITLE
Lack of documentation regarding feeds / synchronisation

### ISSUE THREAD

**Issue by paupaulaz** [MISP/misp-book#238]
Hi,

After setting a MISP instance via https://github.com/harvard-itsecurity/docker-misp, I am trying to fully understand the different synchronization mechanisms MISP offers.

I was able to set up both feed subscription and instances synchronization, but I am struggling to find out in the documentation how and when the sync actions (pulling feeds, pulling / pushing events with sync. instances) are performed. Is supposed to be only triggered by hand ? Is the event list refreshed upon loading ? Is it done in the backend on a regular basis ?

Furthermore, in the case of a feed, what mechanism (if there is one) is in place to make sure only new events are pulled ?

Thank you very much in advance for any help !

**Comment by Wachizungu** [comment]
I believe the stuff I added covers most of your questions, except maybe the feed part. If you have other specific questions please let me know.

**Comment by PROTechThor** [comment]
@Wachizungu Man, I'm loving all your many contributions to MISP-book. Thank you!

**Comment by Wachizungu** [comment]
thank you :D
