### ISSUE TITLE
Usage instructions quite limited

### ISSUE THREAD

**Issue by frennkie** [MISP/misp-book#28]
I tried getting the MISP Book running locally but failed to do so only relying on the notes in the `USAGE` file.
I'm on Ubuntu (15.10 in this case) and finally got it working after doing these steps on a clean installation:
# Install node and npm

```
sudo apt-get install nodejs nodejs-legacy npm 
```
# Install further requirements

```
sudo apt-get install libcairo2-dev libjpeg-dev
sudo apt-get install calibre  # for generating PDFs
```

Might save other people a few minutes if you could include these instructions, what do you think?

**Comment by SteveClement** [comment]
this has been fixed.
