### ISSUE TITLE
Workflow Module Error - Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by ServSlack** [MISP/misp-book#297]
When try to enable " Workflow " plugin in the last version of MISP " v2.4.179 " I received the error below:

When try change setting from command line apparently works, but inside "/var/www/MISP/app/tmp/logs/Config/config.php " nothing change:

2023-11-23 18:54:14 Warning: Warning (2): count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/View/Workflows/error.ctp, line 14]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Workflows/error.ctp, line 14
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
WorkflowsController::beforeFilter() - APP/Controller/WorkflowsController.php, line 24
BetterCakeEventManager::dispatch() - APP/Lib/Tools/BetterCakeEventManager.php, line 23
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2023-11-23 18:54:14 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/View/Workflows/error.ctp, line 16]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Workflows/error.ctp, line 16
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
WorkflowsController::beforeFilter() - APP/Controller/WorkflowsController.php, line 24
BetterCakeEventManager::dispatch() - APP/Lib/Tools/BetterCakeEventManager.php, line 23
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99
![workflow-error](https://github.com/MISP/misp-book/assets/32932095/ead02110-c479-462b-9098-d37d48cc9568)

**Comment by Kagee** [comment]
Replaced by https://github.com/MISP/MISP/issues/9415
