### ISSUE TITLE
example - convention with example organisations

### ISSUE THREAD

**Issue by adulau** [MISP/misp-book#45]
example - convention with example organisations

**Comment by Wachizungu** [comment]
I think you might have fixed this one with https://github.com/MISP/misp-book/commit/dab82f5df656a67fcd36d49a845cdb3600ca7c5a#diff-5c936d4c1f89252d3c805dd0f1b2c7f9c8da4576715cac730751715df26e4fae

**Comment by adulau** [comment]
Indeed ;-) Thank you.
