### ISSUE TITLE
Publish event to ZMQ does not include Objects information

### ISSUE THREAD

**Issue by imereau** [MISP/misp-book#65]
Dears,

Since MISP 2.4.80, we have the possibility to define objects. If you download a sample, the object is automatically created with subsequent attributes (filename, md5, sha1, sha256 and filesize).
However, it seems that this information is not included when publishing the event to ZMQ.

Am I missing something or is it not supported? I am running 2.4.80 on Ubuntu.

Thanks a lot in advance for your help!

BR's
Irving

**Comment by iglocska** [comment]
Interesting. That should work via ZMQ. Could you update to the latest version just in case?

**Comment by imereau** [comment]
OK, sure, I will.
I am actually using both ZMQ and STIX export to populate the TAXII server. I realise that also the STIX export doesn't contain objects information (e.g. hashes related to an uploaded sample are not present, even when marked for IDS).
Is there something I am missing? I am using the /events/stix/download URL without additional parameters.

thanks a lot again!
Irving

**Comment by iglocska** [comment]
Hmm it should include them as of the latest version, @RichieB2B  added it afaik ;)

**Comment by imereau** [comment]
hmhm weird..
I am on:

misp@misp:/var/www/MISP$ cat .git/HEAD
ba71effd12c93d26579d1508d91fcbcb275e7a26
misp@misp:/var/www/MISP$ cat VERSION.json
{"major":2, "minor":4, "hotfix":81}

But still I can't find objects hashes e.g. in the STIX export :-(
Any advise is welcome..

Irving

**Comment by RichieB2B** [comment]
It should.. what object type are you using?

**Comment by imereau** [comment]
I am actually uploading samples, which nicely creates an object with filename, hashes and file size as attributes. And I would need these attributes to be exported in STIX. 
I did not try with another object type to be honest. 

Thx again!
Irving

**Comment by RichieB2B** [comment]
The subject of this issue says ZMQ. Are you using the MISP TAXII service by any chance?

**Comment by imereau** [comment]
Yes, I am. Indeed, it was the original issue. Just a bit of context, I'm using ZMQ to publish events to the MISP TAXII server and the STIX export with custom scripts to freshly load the TAXII server. And I noticed that the objects attributes were not included. Sorry for mixing up the 2 subjects. Actually, more important to me is the STIX export using the MISP API. I can do it all with that functionality only. ZMQ is bonus :)

Many thanks again for your help!
Irving

**Comment by RichieB2B** [comment]
STIX via TAXII (via ZMQ) is an entire different code path. It doesn't support many of the mapping that the straight "Download as..." STIX export does.

I suspect ZMQ itself does pass the MISP objects but the MISP STIX converter from https://github.com/MISP/MISP-STIX-Converter does not.

**Comment by imereau** [comment]
OK understood. 
But what about the STIX export via the API? Is it supposed to include objects info?

**Comment by RichieB2B** [comment]
API as in downloading the /events/stix/download URL will include the objects. Using PyMISP will not include the objects in the STIX format (as it uses the external MISP STIX converter).

**Comment by imereau** [comment]
Well... I upgraded to the latest version and now I get a "An internal Error has Occured" when trying to access /events/stix/download.

2017-10-27 09:36:45 Error: [Exception]
Request URL: /events/stix/download
Stack Trace:
#0 [internal function]: EventsController->stix('download')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

**Comment by iglocska** [comment]
Pushed a fix, git pull and it should work again.

Thanks for the heads-up!

**Comment by imereau** [comment]
cool, it works fine again! Many thanks for the quick fix! :-)

**Comment by shimi199393** [comment]
hi , i working with zmq to update the taxii server . 
you can tell me which script you use for sync stix api to zmq ?

**Comment by shimi199393** [comment]
> cool, it works fine again! Many thanks for the quick fix! :-)

hi , i working with zmq to update the taxii server .
you can tell me which script you use for sync stix api to zmq ?
