### ISSUE TITLE
Use GPG consistently

### ISSUE THREAD

**Issue by StefanKelm** [MISP/misp-book#76]
Okay, this is super-nitpicky...  :-)

The book uses "GPG", "Gpg", "GnuPG", and "PGP". Suggest to use only one term to simplify searching...

**Comment by adulau** [comment]
Good point. I think we are not event consistent on the UI.

I would propose GnuPG (as we rely on the GNU implementation of PGP). Fine for you? @iglocska ok for you? 

If we are fine, I'll update it on both side (MISP core and MISP books).

**Comment by StefanKelm** [comment]
@adulau I would choose GnuPG as well.
(yes, the UI is inconsistent as well...  ;-) )

**Comment by SteveClement** [comment]
I went through misp-book and changed it to GnuPG where needed…
