### ISSUE TITLE
Pymisp issue

### ISSUE THREAD

**Issue by claragpalacios** [MISP/misp-book#94]
Good morning ,

I have an issue with Pymisp.

When I try to change/add/delete the tag of any event via web, the event
goes to unpublished status. But,changing/adding/removing the tag via API
(pymisp) does not change the publishing status of that event.

Is that an error?
What would be the method to make these massive label changes through
Pymisp and change the publication status of each event?

Thank you very much in advance.

I look forward to hearing from you.

Greetings.

**Comment by SteveClement** [comment]
@claragpalacios if this is still an issue please open in the [issue tracker]( https://github.com/MISP/PyMISP/issues/) of the [PyMISP](https://github.com/MISP/PyMISP/) repository.
